export const ON_FETCH_HOME_DATA = 'ON_FETCH_HOME_DATA';
export const ON_ADD_NEW_FRIEND = 'ON_ADD_NEW_FRIEND';
export const ON_RESET_STATE = 'ON_RESET_STATE';
export const ON_ADD_NEW_POST = 'ON_ADD_NEW_POST';
